### ISSUE TITLE
[SUGGESTION] Make this button be clicked

### ISSUE THREAD

**Issue by its-pablo** [NanderTGA/windows96-local-2.0#1]
![image](https://user-images.githubusercontent.com/78528552/205812910-f0ae9e19-6a54-445f-add2-aba0971e4103.png)

**Comment by ctrlyy** [comment]
oh fuck right off dude this repository is good

**Comment by NanderTGA** [comment]
Before I block you and close this bullshit issue, let me summarize your behavior incase anyone reads this.

- He nuked a discord server because he didn't like the owner, who trusted him at the time of giving him admin.
- He has also been an asshole to everyone in every server and groupchat, except for windows 93 or 96 maybe.
- He has disrespected @ctrlyy regarding her gender, going as far as deadnaming her, even though I'm quite sure he's been educated on this at his school.
- He thinks I can't get over my ban on windows 96? Yeah I don't get this one either. I have stopped caring about windows 96 a long time ago. This project was already finished before that, and after someone asked me to send it recently, I got the idea to upload it here and put instructions instead of having to tell everyone the exact same things over and over again. Yet he still tries to tell people, including me, I can't get over a ban and am acting "salty" about it.

Now please leave us alone and fuck off. You won't be missed by anyone.
